In [1]:
from keras.models import Sequential
from keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense
import warnings
warnings.filterwarnings("ignore")


### Creating Model

In [2]:
classifier =Sequential()

### Step 1 :convolution 
* input layer/dimension 
* step-1 convolution 
* 64 number of output filters in convolution 
* 3,3 is filter matrix that will multiply to 
* 64,64 is image size 
* 3 rgp


In [7]:
classifier.add(Convolution2D(64,3,3, input_shape=(64,3,3),activation='relu',padding='same'))

#### step2: pooling 
* processing 
* hidden layer 1
* 2,2 matrix rotate ,tilts ,etc to all the images 

In [8]:
classifier.add(MaxPooling2D(pool_size=(2,2),padding='same', data_format='channels_last',strides=(1, 1)))

* adding a second Convolution Layer 
* Hidden Layer 
* Relu turns negative images to 0

In [11]:
classifier.add(Convolution2D(64,3,3, activation='relu',padding='same'))
classifier.add(MaxPooling2D(pool_size=(2,2),padding='same'))

#### step3:Flatten 
* convert the matrix to single array 

In [12]:
classifier.add(Flatten())

# step4:Full connection 
* 128 is the final layer of output & from that 1 will be considerd  Infected and Uninfected

In [14]:
classifier.add(Dense(128,activation='relu'))
classifier.add(Dense(1,activation="sigmoid"))

### Compiling 

In [15]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

# Defining the training and testing 

In [19]:
from keras.preprocessing.image import ImageDataGenerator 

In [20]:
train_data=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)

In [21]:
test_data=ImageDataGenerator(rescale=1./255)

In [22]:
training_set=train_data.flow_from_directory("Malaria Cells/training_set",target_size=(64,64),batch_size=32,class_mode="binary")

Found 27558 images belonging to 2 classes.


In [23]:
test_set=test_data.flow_from_directory("Malaria Cells/testing_set",target_size=(64,64),batch_size=32,class_mode="binary")

Found 15832 images belonging to 2 classes.


In [32]:
classifier.fit(training_set,epochs=10,validation_data=test_set,validation_steps=1000)

Epoch 1/10
862/862 [==============================] - 821s 954ms/step - loss: 0.1549 - accuracy: 0.9523 - val_loss: 0.1572 - val_accuracy: 0.9459
Epoch 2/10
862/862 [==============================] - 912s 1s/step - loss: 0.1474 - accuracy: 0.9545
Epoch 3/10
862/862 [==============================] - 123s 143ms/step - loss: 0.1441 - accuracy: 0.9547
Epoch 4/10
862/862 [==============================] - 69s 80ms/step - loss: 0.1395 - accuracy: 0.9555
Epoch 5/10
862/862 [==============================] - 66s 77ms/step - loss: 0.1397 - accuracy: 0.9563
Epoch 6/10
862/862 [==============================] - 65s 76ms/step - loss: 0.1360 - accuracy: 0.9563
Epoch 7/10
862/862 [==============================] - 64s 74ms/step - loss: 0.1360 - accuracy: 0.9566
Epoch 8/10
862/862 [==============================] - 64s 74ms/step - loss: 0.1319 - accuracy: 0.9579
Epoch 9/10
862/862 [==============================] - 64s 75ms/step - loss: 0.1296 - accuracy: 0.9573
Epoch 10/10
862/862 [================

In [41]:
import numpy as np 
from keras_preprocessing import image
testing=image.load_img("Malaria Cells\single_prediction\Parasitised.png",target_size=(64,3))
testing=image.img_to_array(testing)
testing=np.expand_dims(testing,axis=0)
print(testing)
print(training_set.class_indices)


[[[[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [207. 116. 133.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [205. 114. 131.]
   [  0.   0.   0.]]

  [[  0.   0.   0.]
   [205. 114. 131.]
   [  0.   0.   0.]]

  [[225. 167. 155.]
   [205. 114. 131.]
   [  0.   0.   0.]]

  [[223. 163. 153.]
   [206. 115. 132.]
   [  0.   0.   0.]]

  [[221.

In [43]:
result=classifier.predict(testing)

In [44]:
if result[0][0]==1:
    pred="unifected"
else:
    pred="parasitise"
print("the prediction is :",pred)        

the prediction is : parasitise
